on:
  push:
    branches:
      - main

jobs:
  fix:
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
      cancel-in-progress: true
    environment: fix
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - run: deno task ci:fix

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "🤖 fix"

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - run: deno task cd
